// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clxssqzhzfkqnekrebri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNseHNzcXpoemZrcW5la3JlYnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTU0MDcsImV4cCI6MjA2OTYzMTQwN30.yV9z4m2rv-TABwPgLXQbWDcIkNA34HImHh9emHwguxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});